### ISSUE TITLE
Run Registrar TLD Sync but no result

### ISSUE THREAD

**Issue by Showfom** [centralnicgroup-opensource/rtldev-middleware-whmcs#189]
Hi,

I try to run Registrar TLD Sync  and it shows

```
Fetching TLDs and pricing information. This may take up to a minute. Please wait...
```

Then the text disappears and no result shown on the page

WHMCS version: 8.1
PHP: 7.4

**Comment by papakai** [comment]
Hi again @Showfom 

Please take your time and read our docs regarding the Registrar TLD Sync [here](https://centralnic-reseller.github.io/centralnic-reseller/docs/hexonet/whmcs/whmcs-ispapi-registrar/#importing-prices). Especially check the FAQ entries linked there. If this is still not helpful, let me know. We know the Registrar TLD Sync successfully in use by several customers, I would wonder it not to be working. Important: If you downloaded the package from the Release Overview, also ensure you have downloaded one of the listed "WHMCS Module" archives and not the "Source Code" archive. Sometimes people stumble other that as well.

HTH!

**Comment by Showfom** [comment]
I have already set `max_input_vars` in `php.ini` to 10000, but still same result, the page shows nothing.

The version we installed is v5.1.7 from release page

**Comment by papakai** [comment]
fyi: The load takes about ~30s to 1m. Can you check table "tblerrorlog" if there are related entries available for refernce?

**Comment by Showfom** [comment]
Seems all of them are warning information like 

```
A non-numeric value encountered
templates_c/756edf5bf1d4b36557009e6befc4d8b821164268_0.file.step3.tpl.php
```

**Comment by papakai** [comment]
Can you please provide us your account id at hexonet, to let us check this based on your account.

Please also provide:
- os + version in use

**Comment by Showfom** [comment]
Account on Hextonet is showfom at hexonet dot net

OS: Debian 10
WHMCS: 8.1
PHP: 7.4
Mariadb: 10.5
whmcs-ispapi-registrar 5.1.7

**Comment by papakai** [comment]
ok, thanks. I'll keep you posted.

**Comment by papakai** [comment]
Hi @Showfom,

I temporarily created a user role under your account to give it a try. Worked nicely on our end. Our platform details:

OS: Ubuntu 18
WHMCS: 8.1
PHP 7.4
MySQL: 14.14
whmcs-ispapi-registrar: latest

I don't expect this to be related to Debian (Ubuntu and Debian are highly compatible), so this leads my thinking in direction of Maria-DB. Would you mind to temporarily activate the SQL Debug Mode (General Settings > Other) and retry? Let us see if this brings something useful up. We patched issues with Maria-DB in the past, but new/other Maria DB Software Versions might bump new cases...

We just have no Maria-DB System available to test this on our end as the majority of resellers is using MySQL Server. Still, we know Maria-DB to be faster (we use it in-house too) and therefore worth to ensure it is not incompatible with our Module.

Keep me posted.

**Comment by Showfom** [comment]
I have enabled SQL Debug Mode and run again, but still the same result

On System Module Debug Log page I can see several logs

![image](https://user-images.githubusercontent.com/6773591/121878373-383b2a00-cd3e-11eb-9bb8-dbb39e520016.png)

**Comment by Showfom** [comment]
Mariadb Version 10.5.10-MariaDB-1:10.5.10+maria~buster

I only added the following conf on `/etc/mysql/mariadb.conf.d/50-server.cnf`

```
[mysqld]

sql_mode = NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

**Comment by papakai** [comment]
have you also activated "Log Errors" under "General Settings > Other"? If not, activate it also temporarily together with that SQL Debug flag and try again. If you had this active, then it is fine.
Have new entries reached table "tblerrorlog" ?

**Comment by Showfom** [comment]
It works after enable Log Errors, Display Errors and SQL Debug Mode.

I have no idea but it really works now. I tried to import pricing for 875 TLDs but the page is frozen on text Loading... for more than 5 mins already.

**Comment by papakai** [comment]
Would it be possible to get SSH access to a server and admin area access to the related WHMCS instance?
If so, please open a support ticket at https://hexonet.support/en/new-ticket.php and share the credentials there.

Sorry for asking again: No new entries in tblerrorlog?

**Comment by papakai** [comment]
I gave your hint a try regarding deactivating all these PHP Debug Flags, but it still works on our end.

**Comment by Showfom** [comment]
Hi, I've submit a ticket on Hexonet with my email address.

**Comment by papakai** [comment]
Great, ty. I've replied. Let us continue there. I'll add our findings then finally in here.

**Comment by papakai** [comment]
Closing this issue, as we were not able to identify any issues why it was initially not working, now it does well. Just in case you again experience related issues, please follow-up with us.

Have a nice day @Showfom

**Comment by syedusama997** [comment]
m facing same issue, can you please help me @KaiSchwarz-cnic

**Comment by KaiSchwarz-cnic** [comment]
@syedusama997 

Thanks for reaching out. Do you mind providing all the platform details?

* WHMCS Version
* PHP Version
* DB Software + Version
* Our Module's Version in use
* `max_input_vars` setting's value, see php.ini

**Comment by syedusama997** [comment]
WHMCS Version              8.8.0
PHP Version                     7.4
DB Software + Version               My SQL
Our Module's Version in use
max_input_vars setting's value, see php.ini     10000
list of configured currencies (+ what's the default one)     USD, PKR      USD is default

**Comment by KaiSchwarz-cnic** [comment]
@syedusama997 :

Thanks, we no longer support PHP 7.4 as it has reached end-of-life a while ago. Please step into upgrading to PHP 8.1.

> Our Module's Version in use
That input is missing. A screenshot of the registrar module configuration might help (please ensure hide your account name on that image).

Are there entries in table tblerrorlog? any PHP error you notice?

**Comment by syedusama997** [comment]
when i upgrade it on 8.0 or 8.1 m facing errors "ioncube loader" this extension

**Comment by syedusama997** [comment]
Have you also tried activating error logging/reporting in WHMCS and then to import tlds and prices?
can you please help me in this

Are there entries in table tblerrorlog? any PHP error you notice?
let me check

**Comment by syedusama997** [comment]
![Screenshot 2024-01-09 131446](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/135117535/cfcbead8-31a1-4b1f-a29a-bbb14d1ec1b6)

**Comment by DennisSkov** [comment]
> when i upgrade it on 8.0 or 8.1 m facing errors "ioncube loader" this extension

You need to use IonCube Loader version 12 with PHP 8. See the following: https://docs.whmcs.com/IonCube_Loader_Version_Matrix

**Comment by KaiSchwarz-cnic** [comment]
> Have you also tried activating error logging/reporting in WHMCS and then to import tlds and prices? can you please help me in this

-> https://docs.whmcs.com/Enabling_Error_Reporting

the screenshot related to tblerrorlog isn't that helpful. Nice to know that there are maybe entries in there, but are there entries related to our module? timestamp related to the execution of the TLD & Pricing Import?

In addition, please provide the screenshot of the registrar module configuration - ensure to hide your account name. ty!

**Comment by KaiSchwarz-cnic** [comment]
> > when i upgrade it on 8.0 or 8.1 m facing errors "ioncube loader" this extension
> 
> You need to use IonCube Loader version 12 with PHP 8. See the following: https://docs.whmcs.com/IonCube_Loader_Version_Matrix

Thanks for pointing to that page. Helps us with another customer ticket. Next time a bit earlier please @DennisSkov :heart_eyes:

**Comment by syedusama997** [comment]
@KaiSchwarz-cnic how to hide account name please guide me

**Comment by KaiSchwarz-cnic** [comment]
@syedusama997 use an image editor to either remove the account name or to repaint it with black color.

**Comment by syedusama997** [comment]
sure

**Comment by KaiSchwarz-cnic** [comment]
Closing as we haven't received a follow-up. Feel free to do at later point of time, I'll reopen the issue then.
