### ISSUE TITLE
Cannot be decoded by ionCube Loader 8.1

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#229]
Hi, when I configure PHP 8.1 with the current IonCube, the following error occurs:

`Whoops\Exception\ErrorException: The file /var/www/htdocs/whmcs/includes/hooks/ispapi_transliteration.php encoded as type [1/72] cannot be decoded by this version of the ionCube Loader.
in Unknown:0`

**Comment by PhiGi87** [comment]
how long will it take to fix the problem? I would like to upgrade my WHMCS to PHP8.1.

**Comment by KaiSchwarz-cnic** [comment]
I expect we will have this ready today, latest tomorrow. It is just a change of how we encrypt with ioncube encoder.

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.3.0

HTH / Enjoy
