### ISSUE TITLE
encoded files are reported as corrupt

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#231]
Hi, unfortunately I found a new bug and now I can't edit my domain prices anymore. Look here:

`Whoops\Exception\ErrorException:
The encoded file /var/www/htdocs/whmcs/modules/registrars/ispapi/ispapi.php is corrupt. in Unknown:0
Stack trace:
#0 /var/www/host-on/htdocs/whmcs/vendor/whmcs/whmcs-foundation/lib/Utility/Error/Run.php(0): WHMCS\Utility\Error\Run->handleError(16, '
The encoded...', 'Unknown', 0)
#1 [internal function]: WHMCS\Utility\Error\Run->handleShutdown()
#2 {main}`

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 thanks, and sorry for the circumstances. Looks like either an issue of our encryption or eventually an incompatibility of our encryption with the loader in use on your end. We are already playing around with all that to figure the root cause out.

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.3.1

We played around with our encryption process and it looks like we run in a bug of ioncube encoder. We changed the order of the versions we encrypt with from higher to lower and it worked for us. We'll be reporting this also back to ioncube as their documentation isn't stating something out regarding the order being important. Sorry for the inconveniences caused, we'll be testing produced archives in future as well.

**Comment by KaiSchwarz-cnic** [comment]
One of our customer mentioned that after switching the ioncube loader for PHP from version 11 to 12 helped on his end. Can you ensure that you're using the latest loader version?

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 (and anyone else having this problem): Do you mind sending the below to my hands (kai.schwarz at centralnic.com)?:

* a phpinfo output
* WHMCS Version in use

Thanks so much in advance!

Ioncube asked us to provide this information together with our encrypted + problematic file. Feedback also received from WHMCS and basically we used the right way of encrypting initially. From their point of view. Which sounds good. we just need to figure out where all this still comes from.

**Comment by KaiSchwarz-cnic** [comment]
We identified the issue and solved it. 16.3.4 released:

https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases
