### ISSUE TITLE
PHP version and requirements?

### ISSUE THREAD

**Issue by Archie2024** [centralnicgroup-opensource/rtldev-middleware-whmcs#234]
Not an issue, just an info req...
I looked deeply into your documentation, but I found nothing about PHP version supported and PHP requirements (especially for CNR  Registrar Module )
RRpproxy module required at least PHP 7.3 ... does the new module work with PHP 7.2 too?

**Comment by KaiSchwarz-cnic** [comment]
Hi @Archie2024,

We encrypt the whole software bundle for PHP 7.2 - 8.1 support. In case something isn't working under PHP 7.2 against my expectations, please let us know. We can patch thinks asap.

Best
Kai

**Comment by KaiSchwarz-cnic** [comment]
Dear Customers,

a lot of you were asking if we are ready for WHMCS 8.6 / PHP 8.1 - **Yes, we are WHMCS 8.6 / PHP 8.1 compatible**. We patched all the reported Bugs / the ones we noticed.

Regarding upgrading to WHMCS 8.6 / PHP 8.1, I highly recommend waiting 'til January 2023 if it isn't crucial for you. We have a code freeze starting on 19th of December and upcoming X-Mas Holidays. X-Mas Freedom to the Devs! Please consider this in your planning and support us with a bit of patience.

Wishing you all a white and lovely Christmas!

Best Regards
Kai

**Comment by KaiSchwarz-cnic** [comment]
WHMCS 8.7 is supported.

**Comment by KaiSchwarz-cnic** [comment]
unpinning this issue in favor of #274.
