### ISSUE TITLE
What happened to the ISPAPI module?

### ISSUE THREAD

**Issue by DennisSkov** [centralnicgroup-opensource/rtldev-middleware-whmcs#235]
This is not a bug report, nor is it a complaint. I'm just trying to figure out what happened to this repository 😄

We're only using Hexonet. Do we need to install every module from the bundle?

**Comment by KaiSchwarz-cnic** [comment]
Hi @DennisSkov,

we decided to work on a software bundle to simplify our work (CI pipelines and workflows, Sharing code across modules, ...) and to decrease the upgrade effort for our resellers (1 bundle vs x archives).

Please install the full bundle. Still, no need to activate and use all the modules of course.

HTH
Kai
