### ISSUE TITLE
CentralNic Reseller Domain Plug-In for Blesta / ...

### ISSUE THREAD

**Issue by domaingood** [centralnicgroup-opensource/rtldev-middleware-whmcs#236]
Please create RRPproxy Domain Plug-In for Blesta
https://github.com/blesta/module-namesilo
https://docs.blesta.com/display/user/Namesilo
Domain Registration
Additional domain fields (Extensions)
Domain Transfer
Domain Management
WHOIS Contact Verification (IRTP)
Creating Owner/Admin Contacts on TransferDomain
Domain Locking (Transfer Lock)
Update Contact (Owner/Admin) Information
Nameservers Change
Child Nameserver Management (Add, Modify, Delete)
Explicit Deletions in Admin panel
Domain Renewal
IDNs Support (using idn_to_ascii)
DNS Management (A, AAAA, MX, CNAME, TXT)
Web Forwarding
Email forwarding
Support for OTE testing environment
Support for WHOIS Privacy / ID Protection
Support for Bulk Update Operations
Support for DNSSEC Management

**Comment by KaiSchwarz-cnic** [comment]
Good Morning @domaingood !

I remember you from the HEXONET Blesta Integration. Brand RRPproxy has been renamed to CentralNic Reseller, just fyi.
There are currently no plans with Blesta (and any other 3rd-party Software) regarding CentralNic Reseller . Still, from long-term perspective that would be possible. Nothing we can provide in short to be honest.

Let me keep this issue open for reference and updated in case of news.

Kai

**Comment by domaingood** [comment]
Hello @KaiSchwarz-cnic Can you help me get Sendbox for RRPproxy. So, I can make Blesta module.

**Comment by KaiSchwarz-cnic** [comment]
Find a demo app here:
https://github.com/centralnicgroup-opensource/rtldev-middleware-php-sdk-demo/blob/master/app_rrpproxy.php

the composer.json (the autloader)
https://github.com/centralnicgroup-opensource/rtldev-middleware-php-sdk-demo/blob/master/composer.json

Hope that helps. In addition: Have you already signed up with CNR (CentralNic Reseller)?

**Comment by KaiSchwarz-cnic** [comment]
@domaingood 

Good Morning!

Looks like a misunderstanding on my end. In case you've already signed up with CNR, you can issue OT&E credentials yourself:

Click on the login in the right top corner and go to passwords and security from there and scroll down the corresponding page.

![image](https://user-images.githubusercontent.com/229425/203009500-4aba499a-233b-46a2-90bc-5d952aad3b89.png)

So, username is the exact same one, just the password is a different one - the one you issued there. In WHMCS, then activate the TestMode and it should connect to OT&E successfully.

HTH
