### ISSUE TITLE
README.md error

### ISSUE THREAD

**Issue by Remitur** [centralnicgroup-opensource/rtldev-middleware-whmcs#237]
In README.md this:

This Repository covers the WHMCS Software Bundle provided by the CentralNic Group PLC. Download the ZIP archive including the latest release version here.

the link ( https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/raw/master/whmcs-cnic-bundle-latest.zip ) points to a no-existing page (error 404)

The right link should be this, I guess:
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/raw/main/whmcs-cnic-bundle.zip

**Comment by KaiSchwarz-cnic** [comment]
Thanks for reporting @Remitur!
