### ISSUE TITLE
Aftermarket Domains Toggle

### ISSUE THREAD

**Issue by an0nz** [centralnicgroup-opensource/rtldev-middleware-whmcs#238]
**Describe the bug**
Using ISPAPI v16.6.2 for Hexonet as the WHMCS Lookup Provider some Premium domains return results with a price rather than Unavailable.

**To Reproduce**
1. Set Lookup Provider to ISPAPI
2. Go to Register Domain in WHMCs client area and search for hubforteams.com
3. Result shows hubforteams.com as available along with a price

**Expected behavior**
The domain should be unavailable and only exist for transfer

**Context:**
 - Device: Deesktop
 - OS: AlmaLinux 8
 - Browser Edge 107.0.1418.42
 - WHMCS Version 8.4.1
 - PHP Version 7.4.33
 - ISPAPI Registrar Module Version 16.6.2

**Relevant Logs:**
```
COMMAND = CheckDomains
PREMIUMCHANNELS = *
DOMAIN0 = hubforteams.com

[RESPONSE]
PROPERTY[DOMAINCHECK][0]=211 NOT AVAILABLE
PROPERTY[PREMIUMCHANNEL][0]=AFTERNIC
PROPERTY[PRICE][0]=1200.00
```
```
COMMAND = CheckDomains
PREMIUMCHANNELS = *
DOMAIN0 = hubforteams.com
DOMAIN1 = hubforteams.net
DOMAIN2 = hubforteams.org
DOMAIN3 = hubforteams.biz
DOMAIN4 = hubforteams.info
DOMAIN5 = hubforteams.io

[RESPONSE]
CODE=200
PROPERTY[CURRENCY][0]=USD
PROPERTY[CURRENCY][1]=
PROPERTY[CURRENCY][2]=
PROPERTY[CURRENCY][3]=
PROPERTY[CURRENCY][4]=
PROPERTY[CURRENCY][5]=
PROPERTY[FINALIZATIONDATE][0]=
PROPERTY[FINALIZATIONDATE][1]=
PROPERTY[FINALIZATIONDATE][2]=
PROPERTY[FINALIZATIONDATE][3]=
PROPERTY[FINALIZATIONDATE][4]=
PROPERTY[FINALIZATIONDATE][5]=
PROPERTY[REASON][0]=Domain exists
PROPERTY[REASON][1]=Domain exists
PROPERTY[REASON][2]=
PROPERTY[REASON][3]=
PROPERTY[REASON][4]=
PROPERTY[REASON][5]=
PROPERTY[PRICE][0]=1200.00
PROPERTY[PRICE][1]=
PROPERTY[PRICE][2]=
PROPERTY[PRICE][3]=
PROPERTY[PRICE][4]=
PROPERTY[PRICE][5]=
PROPERTY[CLASS][0]=
PROPERTY[CLASS][1]=
PROPERTY[CLASS][2]=
PROPERTY[CLASS][3]=
PROPERTY[CLASS][4]=
PROPERTY[CLASS][5]=
PROPERTY[DOMAINCHECK][0]=211 NOT AVAILABLE
PROPERTY[DOMAINCHECK][1]=211 NOT AVAILABLE
PROPERTY[DOMAINCHECK][2]=210 Available
PROPERTY[DOMAINCHECK][3]=210 Available
PROPERTY[DOMAINCHECK][4]=210 Available
PROPERTY[DOMAINCHECK][5]=210 Available
PROPERTY[PREMIUMCHANNEL][0]=AFTERNIC
PROPERTY[PREMIUMCHANNEL][1]=
PROPERTY[PREMIUMCHANNEL][2]=
PROPERTY[PREMIUMCHANNEL][3]=
PROPERTY[PREMIUMCHANNEL][4]=
PROPERTY[PREMIUMCHANNEL][5]=
PROPERTY[DOMAINCHECKTIME][0]=0.326
PROPERTY[DOMAINCHECKTIME][1]=0.377
PROPERTY[DOMAINCHECKTIME][2]=0.186
PROPERTY[DOMAINCHECKTIME][3]=0.191
PROPERTY[DOMAINCHECKTIME][4]=0.177
PROPERTY[DOMAINCHECKTIME][5]=0.177
QUEUETIME=0
DESCRIPTION=Command completed successfully
RUNTIME=0.502

QUEUETIME=0
RUNTIME=0.598

EOF
```

**Comment by KaiSchwarz-cnic** [comment]
@an0nz thanks for forwarding. Let me dive into analysis.

**Comment by KaiSchwarz-cnic** [comment]
Hmm... this is basically a feature of our ispapi integration. It is a aftermarket domain name (e.g. hubforteams.com) that your clients could buy that way. Transfers are still working - go to the Transfer Form, input the domain + epp code - voila, you're able to add it to shopping cart.

@an0nz isn't this useful? The domain is getting actively offered via afternic.com and is therefore "available".
Would you prefer having a possibility to toggle that behavior on/off? Something like a Registrar Module Setting that is by default turned off (aftermarket domains not supported) and when turned on, aftermarket domains are supported.

Thanks for sharing your opinion

Best
Kai

**Comment by KaiSchwarz-cnic** [comment]
I just noticed a pricing issue that will be patched tomorrow and if you're interested in that Toggle, I could include it as well.

**Comment by an0nz** [comment]
@KaiSchwarz-cnic that would be a useful toggle. This is causing issues for us as we use the Domains Extended addon, its Domain Transfer uses the search to identify if a domain can be transferred or registered on the same page.

**Comment by KaiSchwarz-cnic** [comment]
[v16.6.5](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.6.5) is out, patching the aftermarket pricing I noticed plus some issues with PHP8.

@an0nz will have an eye on that toggle. thanks for addressing.
