### ISSUE TITLE
unable to register domain with .boo tld

### ISSUE THREAD

**Issue by ryuujinos** [centralnicgroup-opensource/rtldev-middleware-whmcs#242]
**unable to register domain with .boo tld**

Unable to register domain with .boo old with WHMCS module. We receiving X-ACCEPT-SSL-REQUIREMENT and no additional domain fields have been required to the user.

**To Reproduce**
1. place an order to WHMCS for domain.boo
2. accept the order
3. you receive a registration failed error

**Expected behavior**
a successful registration

**Context (please complete the following information):**
 - WHMCS Version 8.5.2
 - ISPAPI Registrar Module Version 16.5.6

**Comment by KaiSchwarz-cnic** [comment]
@ryuujinos thanks for addressing, will be patched tomorrow.

**Comment by KaiSchwarz-cnic** [comment]
![image](https://user-images.githubusercontent.com/229425/220601954-dcb1f13c-75a6-4da1-b6b8-b1dc5390a830.png)

patched via v16.15.7

Enjoy your day! @ryuujinos

**Comment by ryuujinos** [comment]
@KaiSchwarz-cnic I just updated and tested! It works!
thanks
