### ISSUE TITLE
Ioncube

### ISSUE THREAD

**Issue by marbman21** [centralnicgroup-opensource/rtldev-middleware-whmcs#243]
Getting the following error on PHP 8.1 and ioncube 12 loader:

/includes/hooks/ispapi_transliteration.php encoded as type [1/72] cannot be decoded by this version of the ionCube Loader. "php81-php-ioncube12"

WHMCS V8.6.1

**Comment by KaiSchwarz-cnic** [comment]
for reference for others: please upgrade to a newer version of our software bundle. it supports whmcs 8.6 + php8.
also ensure to use the latest ioncube loader version.
