### ISSUE TITLE
authcode & registrarlock for .de domains

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#245]
**Describe the bug**
Unfortunately, it is not possible to create the AuthCode or remove the registrar lock for .de domains. If you want to create the AuthCode, an error appears that the lock must first be removed. If I want to remove the lock, the error comes that an AuthCode must first be created. I'm massively irritated.

`DOMAIN.de: Failed loading the epp code. Please unlock this domain name first to get a new epp code set by the registry provider. Access it later on here.`

`Domain Registrar Command: Toggle Registrar Lock - Failed: DOMAIN.de: Unable to remove registrar lock. [Missing required attribute; AUTH]`

I always use the latest version of the WHMCS domain module!

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 

Thanks for reaching out. Is this related to the ISPAPI Registrar Module or to the CentralNic Reseller Registrar Module?

Kai

**Comment by PhiGi87** [comment]
Sorry, ISPAPI

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v16.15.21

It is generating now a random auth for .de domains and auto unlocks them.

HTH
