### ISSUE TITLE
nameserver & contact details

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#246]
**Describe the bug**
The following problems occur with Domain Transfer IN:
- The (new) name servers are not set - I assume because the zones have not yet been created?!
- The new contact details / handles are NOT stored in the domain. We have now transferred more than 300 domains with the WHMCS module, and the handles were not set correctly for any domain.

I can't find any error messages. I currently don't know why this is happening.

I always use the latest version of the WHMCS domain module!

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87

Thanks for reaching out. I need some more details:

* Registrar Brand in use: ISPAPI or CNR?
* is this related to the Migration Tool or normal Transfers over the respective Registrar Module?

Thanks so much!

**Comment by KaiSchwarz-cnic** [comment]
@PhiGi87 

Some feedback from our end in advance. Our docs explain the below Registrar Module Settings:

> Activate **Automatic NS Update** setting in case you want our module to update domain’s nameservers automatically after successful transfer. Just a little note: WHMCS itself by default suggests your configured default nameservers. This setting will automatically update the nameservers after successful transfer without knowing if the customer set these nameservers or if WHMCS did it. Removing all nameservers from input fields in step Configure in WHMCS’ Shopping Cart won’t change anything as WHMCS keeps then using the default nameservers. So, be aware of that design issue of WHMCS for Transfer Orders when using that feature. Read [FAQ Entry #25](https://centralnicgroup-public.github.io/rtldev-middleware-documentation/docs/hexonet/faqs/whmcs-ispapi-registrar/#25-nameservers-not-updated-after-transfer) for more details.

> Activate **Automatic Contact Update** setting in case you want our module to update your .com/.net/.cc/.tv domain’s contact details automatically after successful transfer. The mechanism will care about updating the related registrant contact details to the data of the client who initiated the transfer. It also cares about updating admin/tech/billing contact details as configured in WHMCS. This mechanism will only be updating domain names where we were not able to parse Contact Details out of WHOIS Data after successful transfer because of active WHOIS Privacy / id protection service (Hint: “Redacted for Privacy”).

Do you have those settings turned on?

We have a bigger release upcoming (2023-Q1) including several new features / major changes and few minor patches. There, we also introduce a review of the Automatic Contact Update mechanism to support all TLDs.

WHMCS is promising "web hosting made easy" and has therefore its internal processes (Registrations, Renewals, Transfers, ...) integrated in a very similar way while ignoring domain industry specifics. The communication between Registrar and Registry Provider happens based on EPP Protocol and this one isn't allowing for contact updates to be included in transfer process while whmcs is expecting this to be covered. Just providers of some exotic ccTLDs allow for that as they do not follow the standard epp protocol. Finally, the registrar has to cover such things in the way of a post-transfer update process. That's what we do. Still - this leads to other issues: Contact Updates might lead to a change of registrant ending in IRTP or a Domain Trade. The later one is for some TLDs not free of charge and WHMCS is not invoicing those costs. We are logging them up to now the WHMCS ActivityLog for transparency. We addressed the missing Core Integration of Domain Trades to WHMCS years ago - no big interest in covering that on their end up to now.

**Comment by KaiSchwarz-cnic** [comment]
The new Mechanism has been released with 17.0.0. As we haven't received further feedback -> closing.
