### ISSUE TITLE
IBS: 504 Gateway Timeout, issues with .it & RegisterDomain

### ISSUE THREAD

**Issue by Kian987** [centralnicgroup-opensource/rtldev-middleware-whmcs#254]
Hi,

sadly the current state of IBS isn't good. It is not usable. Even the most basic features are no longer reliable. Keep in mind what I am describing is occurring on multiple systems of different providers that are using a wide variety of WHMCS versions.

### 504 Gateway Timeout still occurring

First thing first, what I described [here](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/issues/253) last week is still happening. The same exact module on some systems still causes 504 Gateway Timeout. On some others it works. I have no idea why `getconfigarray` / `Account/Balance/Get` requests keep flooding IBS API server. The only option these providers have is to keep using IBS v1 module.

### Wrong validations, values... wrong everything

Second. It seems that today we have lost the ability to register some .it domains but I suspect the issue also applies to other extensions since the principle is the same.

I also think that the issue is not directly caused by the module. IBS API probably plays a role here. Maybe IBS changed something on their side but such changes are unknown to WHMCS module.

Take a look at the following screenshot (left side request, right side response).

![ibs_bug](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/68689332/de71562d-5b13-4347-bf4a-270c9d2d18da)

As you can see we have errors everywhere that don't make any sense:

- Firstname is present and valid but according to IBS API firstname is missing
- Lastname is also fine but IBS API says it is invalid. Don't tell that for IBS having apostrophe in lastname is considered error
- The value of `registrant_dotitregcode` depends on `registrant_dotitentitytype`. For natural persons (1) like in this case, it is equal to Tax ID / Codice Fiscale. It's a value that looks like follows `RSSMRA70A41F205Z` - this one is fake but valid. Now according to IBS `Fiscal code birthday does not validate`. This makes absolutely no sense! The birthday of the customer in question is perfectly valid. I suspect IBS implemented a check for italian Tax IDs but they failed. Their validation isn't working

### Update contacts still not working

Last week when I opened my [first bug report](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/issues/253) all we wanted was the ability to restore a feature that stopped working without notice. I am talking about updating domain contacts (tech, registrant, billing).

Now not only this feature is still not working but providers are experiencing Gateway Timeouts, inexplicable errors and validations that make no sense.

**Comment by KaiSchwarz-cnic** [comment]
**504 Gateway Timeout** -> we moved the validation of API connectivity now out of `getConfigArray` to `config_validate`. A undocumented way we got forwarded by WHMCS customer support.

So, any issue related to **504 Gateway Timeout** I consider as patched from Code Perspective. You're receiving that error as result of making to many requests for a certain time interval. If this still occurs, please open a support ticket and include the affected account name so that technicians can check if it got blacklisted because of this.

**Comment by KaiSchwarz-cnic** [comment]
The issue with .it registrations, I opened an internal task for the IBS Backend Devs to have an eye on it. I'll keep you in the loop.

**Comment by KaiSchwarz-cnic** [comment]
@Kian987 phew :dancers: 

Let me see what I can do... Thanks for that feedback, very helpful.

**Comment by KaiSchwarz-cnic** [comment]
@Kian987 regarding the .it registration you addressed: we received the html entity in the lastname - is that part of customer data?
Can you check that please?

**Comment by KaiSchwarz-cnic** [comment]
@Kian987 just fyi as it is .it related - 4.0.7 patched an issue with TransferDomain (registrant_dotitnationality).

**Comment by Kian987** [comment]
As for `savecontactdetails` (or `Domain/Update`) that never works since always, I found out why.

The page from which endusers update their details (`clientarea.php?action=domaincontacts&domainid={DOMAIN_ID}`) doesn't pick up additional domain fields. The problem occurs with all TLDs that require at least one mandatory additional domain field.

I don't know if the page in question is supposed to iterate over additional domain fields so that such fields can be seen and edited or if the module just loads them automatically on save (no edit supported), but for sure IBS module does is not transmitting any additional field.

That's why the update never works from years. It can only works with TLDs that do not have any mandatory additional field.

**Comment by KaiSchwarz-cnic** [comment]
> The page from which endusers update their details (clientarea.php?action=domaincontacts&domainid={DOMAIN_ID}) doesn't pick up additional domain fields. The problem occurs with all TLDs that require at least one mandatory additional domain field.

Yes, that's the design of WHMCS. If I recall correctly, the IBS Integration has a additional fields sub menu entry on client area. There such fields can be filled and submitted and finally followed by the Contact Data update. The design of whmcs is in that regard not following best practices ... In Registrar Frontends, you always see the contact data form together with additional domain fields (which makes sense to avoid a two-step update process).

WHMCS is including the fields then in $params when contact data is submitted. In case there's nothing broken with the module, the fields are mapped into the API Command and included in the API request.

The IBS Integration isn't therefore the bad guy, it starts with WHMCS in 1st line - still, I'll have to check .it fields after the findings for the IBS API have been patched (you initial reported case) - they are on it.

**Comment by KaiSchwarz-cnic** [comment]
A patch has been rolled out for the .IT registration on API-side. The only thing questionable to us is: “d&#039;Alessandro” which is indeed invalid and should be “d'Alessandro“. Where is that exactly coming from?

I checked the HEXONET integration and there, we do have an explicit html_entity_decode call in place. Looks like WHMCS is messing up the data for some reason -> I could imagine the Transliteration Process to have an impact.
https://docs.whmcs.com/Custom_Transliteration

WHMCS comes with a default integrated transliteration which could be the cause or if you have a custom one in place, that one. Just my two cents.

I took now the hexonet solution over and I guess that will do the trick. v4.0.8 is out.

**Comment by KaiSchwarz-cnic** [comment]
@Kian987 I moved the additional field topic out to a separate github issue and explained it there again. We'll keep that one updated, but as there's a way provided via IBS - we consider it as not urgent which leaves us also time for digging deeper and playing around with child themes, hooks, ... and talking to WHMCS.
