### ISSUE TITLE
Error when trying to register a .dk domain

### ISSUE THREAD

**Issue by OrangeJuiced** [centralnicgroup-opensource/rtldev-middleware-whmcs#259]
**Describe the bug**
The following error occurs when trying to register a .dk domain: "An unknown error occurred".

**Comment by KaiSchwarz-cnic** [comment]
@OrangeJuiced sorry for the delay, I had been ooo.

* What's the registrar module in question?
    * IBS, HEXONET, CentralNic Reseller?
    * the module shipped with WHMCS or part of our Software Bundle?

Thanks!

**Comment by KaiSchwarz-cnic** [comment]
@OrangeJuiced 

As we've not recevied feedback received, I've to close this issue. We're alway happy to help, but need some more details. Feel free to follow-up anytime. Closing for now.
