### ISSUE TITLE
error "An issue was encountered while retrieving the DNS records. Please contact support."

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnicgroup-opensource/rtldev-middleware-whmcs#260]
WHMCS 8.13
RRPproxyv19.1.3
in DNS managmant,error message below
![20230823_1692795993.jpg](https://7up.pics/images/2023/08/23/20230823_1692795993.jpg)

**Comment by KaiSchwarz-cnic** [comment]
Hey @jsjcjsjc,

The error message you noticed is coming from WHMCS Core. A common error message not giving you a hint why the DNS Update failed. I can confirm that our registrar module if forwarding the exact error message to WHMCS, but WHMCS is just showing that common error message. A design issue of WHMCS imho. An improvement for this is in work on our end as such basic things should be better covered by WHMCS. The exact error message of that dns update can be identified in the Module Log. We are working on an entire improvement of that section. What you notice here is how Team WHMCS has designed the dns management which isn't customer-friendly nor is it making the dns management a success.

if you need further help with that dns update, please follow-up. hopefully the error message in module log is helping you already.

**Comment by jsjcjsjc** [comment]
> Hey @jsjcjsjc,
> 
> The error message you noticed is coming from WHMCS Core. A common error message not giving you a hint why the DNS Update failed. I can confirm that our registrar module if forwarding the exact error message to WHMCS, but WHMCS is just showing that common error message. A design issue of WHMCS imho. An improvement for this is in work on our end as such basic things should be better covered by WHMCS. The exact error message of that dns update can be identified in the Module Log. We are working on an entire improvement of that section. What you notice here is how Team WHMCS has designed the dns management which isn't customer-friendly nor is it making the dns management a success.
> 
> if you need further help with that dns update, please follow-up. hopefully the error message in module log is helping you already.

thanks, after close "TestMode", it ok now

**Comment by rocketdomains** [comment]
May I ask if Blesta is better than WHMCS in this regard?

Kind regards,
Frazer

**Comment by KaiSchwarz-cnic** [comment]
Cheers, Frazer!

Our integration with Blesta is very basic and even though I've been asking for it, it is not getting some priority atm. Especially when it comes to Domain Addons - id protection, email forwarding, dns management - the module isn't if I recall correctly supporting that. My honest opinion on Blesta: it is far behind a easy to understand UI (compared to WHMCS). HostBill is definitely a better choice if you want to continue without big hussle. I heard good things from customers switching from WHMCS to HostBill. Blesta made a big improvement step with their Domain Manager (v5) already. That's my personal experience with Blesta: While it was easy to me starting with WHMCS, I struggled with Blesta (regarding setting it up, but also covering developments).

Hope that helps.

**Comment by KaiSchwarz-cnic** [comment]
For rounding this up:
With our recent bundle version the exact API error message is now getting shown in the DNS Management section to ensure it is visible to the client. You'll have to apply template changes to make this happen. 

More details available in the release notes of [v21.0.0](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v21.0.0). Check the "BREAKING CHANGES".
