### ISSUE TITLE
Precheck DNS Management not work if using CNIC Domain Search

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnicgroup-opensource/rtldev-middleware-whmcs#264]
WHMCS 8.13
RRPProxy 19.13
Hi
it looks like Precheck DNS Management/Precheck Email Forwarding/Precheck ID Protection not work if using CNIC Domain Search
![imagec99f8c4c3ec0ff38.png](https://7up.pics/images/2023/08/26/imagec99f8c4c3ec0ff38.png)

**Comment by KaiSchwarz-cnic** [comment]
Good Day @jsjcjsjc,

What exactly isn't working for you? You screenshot shows as well that addons are getting automatically prechecked? If you click on continue, you'll see that those addons are then activated for the shopping cart item. I tried this out on my end, works perfectly well.

Thanks!

**Comment by jsjcjsjc** [comment]
> Good Day @jsjcjsjc,
> 
> What exactly isn't working for you? You screenshot shows as well that addons are getting automatically prechecked? If you click on continue, you'll see that those addons are then activated for the shopping cart item. I tried this out on my end, works perfectly well.
> 
> Thanks

sorry, this picture comes from normal search UI,there is no precheck if I search in CNIC domain search

**Comment by KaiSchwarz-cnic** [comment]
> sorry, this picture comes from normal search UI,there is no precheck if I search in CNIC domain search

I did tried it out via CNIC domain search previously and it worked. This feature is basically not specific to a domain search. It just happens on shopping cart level initiated via hook.
Do you mind sharing a desktop video with us (or multiple screenshots) showing your navigation and actions showing how it comes to the issue?

**Comment by KaiSchwarz-cnic** [comment]
@jsjcjsjc Thanks, that's very useful feedback. I forwarded this to the responsible Developer. We'll keep you in the loop.

**Comment by KaiSchwarz-cnic** [comment]
We'll be releasing an update for the domain search related to this. The idea here is that we offer our own Checkout Links which will be leading to the configuration page of the shopping cart. With submitting that page the addons will be included (as they were pre-selected). We just can't add items to shopping cart with those addons booked - some resellers are selling those addons for money and it must be the customer himself adding them to the Item. Not something we can/should to on our end. If someone is using the shopping cart of WHMCS - well then he is skipping the entire configuration part of the shopping cart items (missing additional fields, ...). Sadly the WHMCS Shopping Cart Icon can't be configured to point to the configuration page...

Keep looking for the Domain Search update - it will be launched either today or tomorrow.

Hope that helps!
