### ISSUE TITLE
MX Record Problems

### ISSUE THREAD

**Issue by PhiGi87** [centralnicgroup-opensource/rtldev-middleware-whmcs#267]
**Describe the bug**
There is a problem when entering and managing MX Records. They appear to be created once, but when you then try to update the record again in WHMCS, you get the error that there are two identical entries:
Invalid attribute value; duplicate record [domain.com. 3600 IN MX 100 mx.ispapi.net.] 

**To Reproduce**
1. Go to dns records
2. Create a MX record and Save
3. Create a second Record (a, aaaa, or whatever) and klick Save...

**Context (please complete the following information):**
 - WHMCS Version 8.7.2
 - PHP Version 7.4
 - ISPAPI Registrar Module Version 21.2.1

**Comment by AsifNawaz-cnic** [comment]
Hi @PhiGi87 

Hello, thank you for reporting this issue. We are currently inspecting the cause of the problem and will give you an update as soon as possible. We apologize for any inconvenience this may have caused you.

Thank you for your patience and cooperation.

**Comment by KaiSchwarz-cnic** [comment]
Hey @PhiGi87 ,

thanks for reporting that issue. patched via v21.2.2.

Hope that helps!
Kind Regards
