### ISSUE TITLE
cnic_validateAdditionalFields() error for TLD that is not with ISPAPI

### ISSUE THREAD

**Issue by Tuomas-dev** [centralnicgroup-opensource/rtldev-middleware-whmcs#269]
In version 20.0 and later if you try to purchase a new domain through client area for a TLD where the registrar is not Hexonet, you will get the following error: 

`ERROR: Error: Call to undefined function cnic_validateAdditionalFields() in /whmcs/modules/registrars/ispapi/hooks.php:544 Stack trace: #0 [internal function]: WHMCS\\Utility\\SafeInclude::{closure}() #1 /whmcs/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): call_user_func() #2 /whmcs/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): WHMCS\\Hook\\Manager->run() #3 /whmcs/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\\Hook\\Manager->validate() #4 /whmcs/includes/functions.php(0): Illuminate\\Support\\Facades\\Facade::__callStatic() #5 /whmcs/cart.php(0): run_validate_hook() #6 {main} {"exception":"[object] (Error(code: 0): Call to undefined function cnic_validateAdditionalFields() at /home/run...', referer: https://domain/cart.php?a=confdomains`

As an example .fi TLD is registered through FicoraEPP so it should not have a reason to prompt ispapi to hook the registeration process. 

 - WHMCS Version 8.7.3
 - PHP Version 8.1
 - ISPAPI Registrar Module Version 20.0 ->

**Comment by KaiSchwarz-cnic** [comment]
Hey @Tuomas-dev,

Thanks so much for addressing that issue. I've reviewed this and patch v21.4.5 is out.
Please upgrade and let me know if that solved it for you as well.

Enjoy your day!
