### ISSUE TITLE
Unable to remove specific additional field

### ISSUE THREAD

**Issue by DennisSkov** [centralnicgroup-opensource/rtldev-middleware-whmcs#270]
How is removing a specific additional field supposed to happen? I've tried a few things, but I'm only able to remove the field for the value, and not the "label".
I need to remove all additional fields for the .eu TLD as we have our own module for Eurid.

**Comment by KaiSchwarz-cnic** [comment]
@DennisSkov our modules (CNIC and ISPAPI) are shipping with the Additional Domain Fields built-in. Our fields are only returned in case the TLD / domain is assigned to our module.
Means, in your case where the TLD is assigned to another module, you see the fields shipped with WHMCS.
Just follow this article, it nicely covers: [how to remove the standard WHMCS fields](https://docs.whmcs.com/Additional_Domain_Fields#Remove_a_field).

Enjoy!
