### ISSUE TITLE
Premium Domain Issues (at Regular Price / Unavailable)

### ISSUE THREAD

**Issue by x011** [centralnicgroup-opensource/rtldev-middleware-whmcs#272]
**Describe the bug**
Premium Domains shown as available at regular price

**To Reproduce**
Search any premium domain.

**Expected behavior**
Create a setting on module to enable or disable premium domains. Show the correct price if enabled.

**Context (please complete the following information):**
 - OS: Ubuntu 22.04
 - WHMCS 8.8.0
 - PHP 8.1
 - RELEASE:  v21.6.7 

![2023-11-04_23h45_26](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/4313821/9edb9100-c2c6-4e3e-b5d2-7703c2deac8f)

![2023-11-04_23h45_36](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/4313821/5f94c740-8745-4546-959d-b9289b6be70c)

**Comment by DennisSkov** [comment]
Do you have premium domains enabled in WHMCS?
Premium domains have the correct pricing for us.

**Comment by x011** [comment]
> Do you have premium domains enabled in WHMCS? Premium domains have the correct pricing for us.

Yes, we do have Premium Domains enabled.

![2023-11-04_23h53_25](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/4313821/01b0950d-6b5b-4ec5-8a01-139469835ac9)

**Comment by DennisSkov** [comment]
Are you also using the module as the lookup provider?

**Comment by x011** [comment]
Hi Dennis,
After enabling CentralNic Reseller as Lookup Provider, premium domains queries return **unavailable**. Any idea why this may be happening? 

![2023-11-05_12h09_11](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/4313821/32a1d91e-c2cf-4ab4-94c3-e89bc5601f9b)

![2023-11-05_12h10_52](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/4313821/9448b2e8-3a0c-4b8d-b0f3-af120f1dd881)

**Comment by KaiSchwarz-cnic** [comment]
Good Day @x011!

Thanks @DennisSkov for helping here with the initial step for premium domain support! :-)

Related Resources:

* https://docs.whmcs.com/Premium_Domains (for resellers)
* https://docs.whmcs.com/Domain_Pricing#Premium_Domains (for resellers)
* https://developers.whmcs.com/domain-registrars/premium-domains/ (for integrators/registrars)

The last resource is pointing us to a sample registrar module/integration. Let me point you to the related lines of code for a better understanding regarding the technical mechanism behind all that:
https://github.com/WHMCS/sample-registrar-module/blob/master/modules/registrars/registrarmodule/registrarmodule.php#L907-L916

Here, WHMCS asks the underlying Registrar Module to include the premium domain pricing in the availability check which means we as registrar have to return a pricing with the related currency.

We cover that via CentralNic Reseller API in the following way using CheckDomains:
<img width="285" alt="image" src="https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/assets/229425/56be1d7b-46ba-4bdc-aeb2-f0660d922ed0">

Here, you see that the premium price the respective reseller will pay, is returned and this is what we return to WHMCS.
WHMCS will then be adding additional costs (the configured premium domain markup, id protection / dns management / email forwarding addon pricing if applicable etc.) which corresponds finally to the pricing whmcs is displaying on client area and your clients would have to pay.

Let us come back to the pricing we return to WHMCS. You noticed that we are returning that pricing in a specific currency. Here it starts getting weird... If this currency is not configured in WHMCS, WHMCS will show it as available but for the regular pricing.
The currency returned corresponds to the account currency you have at CNR. Our expectation is that returning this currency is resulting in a higher chance for a match with the default currency in whmcs. So, if you enable the Module Log and check for command `CheckDomains`, you'll be able to identify the currency returned.

In your case, WHMCS is returning best.day as unavailable. The important points to cover are here:

* ensure to use OUR registrar module (we can't offer support for the built-in registrar module for technical reasons) ✅
* ensure the lookup provider is the CNR Module ✅
* ensure Premium Domains are activated in WHMCS ✅
* ensure to have the currency in question configured in WHMCS
* ensure to activate the respective TLD your CNR account via CNR Frontend 
* ensure to activate Premiums Domains in your CNR account via CNR Frontend 

Especially the last two points are different to other registrars like HEXONET and often not known / self-explaining-

Hope that detailed information helps!
Still, if you need further help, please follow-up. Provide then the Response of `CheckDomains` from the Module Log please as well.

Kind Regards

**Comment by KaiSchwarz-cnic** [comment]
Sorry for all the updates a made, but now the response i complete. 💯

**Comment by x011** [comment]
I wasn't aware that I needed to activate the Premium Domains on the CentralNic Resellers dashboard. Once this was activated, the premium domain feature functioned properly on WHMCS. Thank you so much, @KaiSchwarz-cnic and @DennisSkov.

**Comment by KaiSchwarz-cnic** [comment]
Just for reference. I brought anything I had in mind together in this guide:
https://support.centralnicreseller.com/hc/en-gb/articles/24671568440221-WHMCS-Premium-Domains

It shows clearly up the software design issues of WHMCS Core around Premium Domains. Feel free to add your feedback in here (if there's something missing, not clear enough).
