### ISSUE TITLE
WHMCS: which version of MySQL, PHP, ioncube loader?

### ISSUE THREAD

**Issue by pavons** [centralnicgroup-opensource/rtldev-middleware-whmcs#274]
Hello @KaiSchwarz-cnic,

Is WHMCS v8.8 supported?

What is the minimum php version that can I use with the latest release (v21.6.8)? 

Is php73 still supported? (as I can seen on my prev issue #227 and also this release note: https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v8.3.1 but on this issue https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/issues/234#issuecomment-1333803002 I see that the php 7.x support was dropped)

Can you please clarify?

**Comment by KaiSchwarz-cnic** [comment]
Php 8
We stopped supporting versions that reached EOL.

🙋‍♂️

**Comment by KaiSchwarz-cnic** [comment]
fyi:
* PHP 7 supported until v23.7.4.
* PHP 8 supported since v23.7.5

we planned releasing PHP 8 only support with the next major version v24, but a software dependency of us (phpseclib) did not consider semantic versioning principles and released PHP 8 support over a patch version. So, by that this came a bit earlier, just unexpected for us.

**Comment by pavons** [comment]
Thanks @KaiSchwarz-cnic for the info.
Very appreciated.

**Comment by mselner** [comment]
Hello, I'm getting this error: The file /var/www/whmcs/docs/modules/addons/cnicdns/cnicdns.php encoded as type [1/81] cannot be decoded by this version of the ionCube Loader

Environment:
FreeBSD 13.3.p7
PHP 8.2.23 (cli) (built: Sep 10 2024 01:34:37) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.23, Copyright (c) Zend Technologies
    with the ionCube PHP Loader v13.0.2, Copyright (c) 2002-2023, by ionCube Ltd.
    with Zend OPcache v8.2.23, Copyright (c), by Zend Technologies
WHMCS 11.0.2

I believe this means that the rtldev-middleware-whmcs software is compiled with IonCube for PHP8.1. 
Do you have a schedule for releasing a version for PHP8.2 or 8.3? 
Thank you

**Comment by KaiSchwarz-cnic** [comment]
@mselner, thanks for reaching out!

Yes, you're right that we're by that not yet ready for PHP 8.2. PHP8.3 isn't yet supported by WHMCS, so no.
Please downgrade to PHP8.1 and ioncube Loader v12.0.1 for now. I keep this thread in the loop regarding PHP 8.2 support.

Kind Regards

**Comment by Remitur** [comment]
> Please downgrade to PHP8.1 and ioncube Loader v12.0.1 for now.

AFAIK, Ioncube is (or should be...) backwards compatible: so Ioncube 13.0.2 should be ok also with PHP 8.1 (I have an install where Ioncube 13.0.1 is working fine with PHP 7.2.34...)

**Comment by KaiSchwarz-cnic** [comment]
@Remitur yes, good point - I fully agree. I just reflected the setup covered by whmcs for PHP 8.1.
Thanks so much for helping others and by that supporting us and our work. Very much appreciated!

**Comment by AsifNawaz-cnic** [comment]
Hi @mselner,

Thank you for reaching out.

We are pleased to inform you that we have just released a new version of our WHMCS Software Bundle ([v24.3.0](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v24.3.0)). This update includes support for PHP 8.2, IonCube Loader v13+, and WHMCS v8.11+.

If you have any further questions or concerns, please feel free to reply to this issue.

Best regards!

**Comment by mselner** [comment]
Hello,

v24.3.0 seems to be working with PHP8.2 and IonCube v13+. Thank you!

I have a few other WHMCS issues to work through and once that is done I will do some testing of the registrar module.

Thank you

Mike

**Comment by KaiSchwarz-cnic** [comment]
For anyone upgrading to v25.0.0 -> we finally had to drop support for PHP7 encryption. PHP8 is now a must have.
Use older versions  (v24 or even lower) of our package, if you're looking for PHP 7.4 support. PHP 7.4 reached EOL already long time ago and dropping support for it, is step helping us to simplify our development work and to benefit also from new language features coming with PHP 8.

Thanks for your understanding.

**Comment by KaiSchwarz-cnic** [comment]
fyi (if you're looking for that): PHP 8.2 is now officially supported with WHMCS 8.13. We'll add support for it asap as well.

**Comment by KaiSchwarz-cnic** [comment]
ok, PHP 8.2 support I noticed already as available and I've been confused by a customer support case. Still, we let me point out that with v27.2.2 of our software bundle, we encrypt with ioncube encoder v14.0.2 and are using ioncube loader 14.4.0 for decrypting.
The version of ioncube encoder also supports PHP 8.3 and by that we can add PHP 8.3 support as well as soon as WHMCS is announcing that.
