### ISSUE TITLE
.it missing description for PIN

### ISSUE THREAD

**Issue by DennisSkov** [centralnicgroup-opensource/rtldev-middleware-whmcs#276]
When registering a .IT domain, registrants are required to enter a PIN.
There's no description for what to insert in this field, however. 

It would be great to have a description shown.

**Comment by KaiSchwarz-cnic** [comment]
[v22.7.3](https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v22.7.3)

voilà! :gift:
