### ISSUE TITLE
Exception with php7.3 and ionCube24 v13.0.2

### ISSUE THREAD

**Issue by pavons** [centralnicgroup-opensource/rtldev-middleware-whmcs#280]
Hi @KaiSchwarz-cnic,

**Describe the bug**
After upgrading to v23.10.7 we see this error on WHMCS admin area (we are using v21.6.9 and works fine with php7.3 and ionCube24 v13.0.2):
```
Whoops\Exception\ErrorException: The file /application/public/manage/includes/hooks/ispapi_transliteration.php cannot be run by the ionCube Loader. Please ask the script provider to supply an encoded file that can run on your version of PHP, 7.3. in Unknown:0
```

**To Reproduce**
1. Update to v23.10.7

**Context (please complete the following information):**
 - WHMCS Version 8.10.1
 - PHP Version 7.3.33
 -  ionCube24 v13.0.2

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/issues/274#issuecomment-2182802148

That version is not compatible to PHP8. This has been brought to your attention in the above ticket.
We highly recommend switching to PHP8.

**Comment by pavons** [comment]
You're right, I forgot about that. Thanks for the reminder.

**Comment by DennisSkov** [comment]
You _might_ be able to use PHP 7.4 if you want to stay on PHP 7 - but I'd recommend updating to PHP 8, unless you have a very good reason to use a PHP version that's unsupported.

**Comment by KaiSchwarz-cnic** [comment]
That's interesting @pavons - we stumbled over issues with phpseclib pointing us to the deprecation of PHP7. I double checked this for their latest version as well, you're right about that they mention `php: >=5.6.1`. 

If I recall correctly, it was about their sw dependency `"paragonie/constant_time_encoding": "^2|^3"` which is supporting PHP8 with version 3. Still, I see their version 2 mentioned as part of the composer.json which is still compatible to older php versions.

Let me check that again on our end, I don't recall the exact scenario, just that composer was facing us with php7 related issues when installing software deps.

**Comment by pavons** [comment]
No problem @KaiSchwarz-cnic, thank you so much.

I'll try to figure out upgrading to a latest supported php version or upgrading to a latest version of this module that support php73 just for now.
