### ISSUE TITLE
modules/registrars/cnic/hooks.php breaks configuratessl.php for other modules

### ISSUE THREAD

**Issue by cenourinha** [centralnicgroup-opensource/rtldev-middleware-whmcs#282]
**Describe the bug**

We use [GoGetSSL WHMCS Module](https://github.com/gogetssl/whmcs-addon) to provide SSL Certificates to our customers and after recently updating the CNIC modules in our WHMCS instance, our clients started getting errors when generating their CSR.

After hours of debugging, we were able to identify that this situation was being caused by the file modules/registrars/cnic/hooks.php in your module.

We are both Central Nic Reseller (previously rrpproxy) and Hexonet domain resellers, but have no interest in resell your SSL Certificates. Please make sure your modules changes don't mess with other modules functionality.

Additionally, please consider open sourcing your modules. This will make it easier to customize, debug, or fix potential problems that may be caused by them.

**Comment by KaiSchwarz-cnic** [comment]
Good Morning!

> After hours of debugging, we were able to identify that this situation was being caused by the file modules/registrars/cnic/hooks.php in your module.

Some more details in that regard? What did you identify there? Any errors you might have seen on screen? Log entries? tblerrorlog? screenshots?

> after recently updating the CNIC modules in our WHMCS instance, our clients started getting errors when generating their CSR.

That means? what was your earlier version in use? which version are you using now?

> Please make sure your modules changes don't mess with other modules functionality.

That's what we usually do, but as we are all human ... That's also why it is that important getting such issues reported in more detail (as far as possible). There are tons of other modules on the market and finally, there's also WHMCS Core. Testing everything is by that impossible. We noticed for example that WHMCS Core is for example implementing some ClientArea hooks in a way that doesn't avoid collisions. Means Provider A can override Provider B's returned data. Do you mind providing more input therefore?

**Comment by KaiSchwarz-cnic** [comment]
ok, let me again come back to the platform details:

- PHP Version
- WHMCS Version
- OS

**Comment by cenourinha** [comment]
- WHMCS 8.8.0
- PHP 7.4
- CloudLinux 8

**Comment by KaiSchwarz-cnic** [comment]
Thanks, PHP 7.4 could play a role. Is it possible for you to upgrade to PHP 8.1 and to test again? Or are you blocked by another party in PHP 7.4?

**Comment by KaiSchwarz-cnic** [comment]
https://github.com/centralnicgroup-opensource/rtldev-middleware-whmcs/releases/tag/v24.5.2

Does that help?

**Comment by KaiSchwarz-cnic** [comment]
Missing feedback. Still, I am sure we patched the issue. In case someone identifies related issues, please let us know.
